[workspace]
resolver = "3"
members = ["./crates/*"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yml = "0.0.12"
url = { version = "2.5.7", features = ["serde"] }
