/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Single = string;
/**
 * 多言語対応文字列または単一言語文字列。
 * 例1："Hello"
 * 例2：{ ja: "こんにちは", en: "Hello" }
 */
export type MaybeLocalizedString = Single | Localized;
/**
 * http・httpsのURL。
 */
export type HttpUrl = string;

export interface Manifest {
  /**
   * マニフェストのバージョン。現在は1のみサポートしています。
   * 将来的にマニフェストの仕様が変わる可能性があるため、このフィールドを使用してバージョン管理を行います。
   * 破壊的変更が行われた場合にのみ、この値が増加します。
   */
  manifest_version: 1;
  /**
   * このマニフェストへのURL。 ない場合は、アップデートチェックが行われません。
   */
  manifest_url?: string;
  /**
   * ユーザーコンテンツの一意な識別子。/^(?<author>[a-z0-9_]+)-(?<content_name>[a-z0-9_-]+)$/ にマッチし、かつ、
   * `-`が連続しない文字列である必要があります。
   * ここで、authorは作者名、content_nameはユーザーコンテンツの名前を表します。
   * コンテンツ名では`-`と`_`をどちらも使用することができ、それらは以下のように使用するべきです。
   * - `-`は概念の区切りに使用する。
   * - `_`は単語の一部に使用する。
   * 例えば、`sevenc_nanashi-aviutl2_rs-ffmpeg_output`は：
   * - 「sevenc_nanashi」という作者の、
   * - 「aviutl2_rs」というものに関する、
   * - 「ffmpeg_output」というユーザーコンテンツ
   * を表します。
   * なお、`content_name`は1単語でも構いません。
   */
  id: string;
  /**
   * ユーザーコンテンツの名前。任意の文字列を指定できます。
   */
  name: string;
  /**
   * ユーザーコンテンツの簡易的な説明。1行で収まるようにしてください。
   */
  summary: Single | Localized;
  /**
   * ユーザーコンテンツのタグ。
   * タグは自由に追加できますが、以下のタグはUIで特別に扱われます：
   * - `#alias`：エイリアス
   * - `#alias-effect`：フィルタ効果エイリアス
   * - `#alias-object`：オブジェクトエイリアス
   * - `#default`：パレット
   * - `#palette`：パレット（#defaultのエイリアス）
   * - `#figure`：図形
   * - `#language`：言語ファイル
   * - `#plugin`：プラグイン
   * - `#plugin-input`：入力プラグイン
   * - `#plugin-output`：出力プラグイン
   * - `#script`：スクリプト
   * - `#script-anm`：アニメーション効果スクリプト
   * - `#script-obj`：カスタムオブジェクトスクリプト
   * - `#script-cam`：カメラ制御スクリプト
   * - `#script-scn`：シーンチェンジスクリプト
   * - `#script-tra`：トラックバー移動方法スクリプト
   * - `#theme`：テーマ
   * - `#transition`：トランジション
   */
  tags?: MaybeLocalizedString[];
  /**
   * ユーザーコンテンツのバージョン。`X.Y.Z(-.+)?`の形式に従う必要があります。
   * 例: "1.0.0", "0.1.0", "2.3.4-beta"
   */
  version: string;
  /**
   * ユーザーコンテンツのバージョン番号。
   * バージョンを比較するために使用します。必ずしも連番である必要はありませんが、バージョンが新しくなるほど大きな値になっている必要があります。
   * 同じversion_numberを持つバージョンが存在した場合は未定義です。
   *
   * このフィールドがないバージョンは常にversion_numberがあるバージョンよりも古いものとして扱われます。
   */
  version_number?: number;
  /**
   * 過去のバージョンのマニフェストへのURL。
   */
  previous_versions?: {
    /**
     * このバージョンのバージョン。
     */
    version: string;
    /**
     * このバージョンのバージョン番号。
     */
    version_number?: number;
    /**
     * マニフェストへのURL。
     */
    url: string;
    [k: string]: unknown;
  }[];
  /**
   * ユーザーコンテンツの作者。
   */
  authors: {
    name: MaybeLocalizedString;
    url?: HttpUrl;
    [k: string]: unknown;
  }[];
  /**
   * ユーザーコンテンツを使用する際の利用規約。
   * このユーザーコンテンツを使用したときの規約のみを記述してください。（例えば、再配布の規約などは含めないでください）
   */
  license: Free | Nicovideo | Custom | Unknown;
  /**
   * ユーザーコンテンツのホームページ。
   */
  homepage?: string;
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  description?: Single | Localized;
  /**
   * 過去のバージョンの変更履歴。
   */
  changelogs?: {
    /**
     * 変更履歴のバージョン。`version`と同じ形式である必要があります。
     */
    version: string;
    /**
     * 変更履歴のバージョン番号。`version_number`と同じ形式である必要があります。
     */
    version_number?: number;
    /**
     * 多言語対応文字列または単一言語文字列。
     * 例1："Hello"
     * 例2：{ ja: "こんにちは", en: "Hello" }
     */
    changes: Single | Localized;
    [k: string]: unknown;
  }[];
  bundles?: RecordHttpUrl;
  /**
   * ユーザーコンテンツのダウンロードURL。
   */
  resources: {
    /**
     * このファイルの取得元。
     *
     * - `http://`または`https://` で始まるURL。
     * - `bundle://{bundle_name}/{path_or_glob}` の形式のURL。{bundle_name}はバンドル名、{path_or_glob}はバンドル内のファイルパスまたはGlobパターンを表します。
     * globパターンを使用した場合、destinationはディレクトリとして扱われ、その中にマッチしたファイルがすべてダウンロードされます。
     */
    source: string;
    /**
     * ダウンロードしたファイルのインストール先。
     */
    destination: string;
    /**
     * このファイルのスコープを指定します。
     * スコープは`[a-z0-9_-]+`にマッチする必要があります。
     *
     * 通常、別のユーザーコンテンツと同じファイルが存在した場合、コンテンツの競合として扱われ、インストールが失敗します。
     * しかし、スコープを指定することで、同じファイルが存在ても、同じスコープである場合に限り、競合を無視してインストールできるようになります。
     * 例えば、スコープを`ffmpeg`に設定した場合、他のユーザーコンテンツに同じファイルが存在しても、そのファイルのスコープが`ffmpeg`であれば競合を無視します。
     */
    scope?: string;
    /**
     * ダウンロードしたファイルのSHA256ハッシュ値。省略可能ですが、指定することを推奨します。
     * 例: "1e9211b2f7152fe7f1b4f4a3c972c8fb56845acd258f03694625d14ee516ec30"
     */
    sha256?: string;
    [k: string]: unknown;
  }[];
  /**
   * このユーザーコンテンツが設定の永続化に使用するファイル。
   * 環境のエクスポート時にこれらのファイルが含まれます。
   */
  configurations?: {
    /**
     * この設定ファイルのパスまたはGlobパターン。
     */
    path: string;
    [k: string]: unknown;
  }[];
  /**
   * このユーザーコンテンツに関する、削除可能なファイルの一覧。
   * ユーザーがこのユーザーコンテンツを削除したときに、これらのファイルも削除されます。
   * また、環境のエクスポート時にはこれらのファイルは含まれません。
   *
   * 例えば、キャッシュファイルや一時ファイルなどを指定します。
   */
  disposables?: {
    /**
     * このファイルのパスまたはGlobパターン。
     */
    path: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * 多言語対応文字列。キーにロケール、値にそのロケールでの文字列を持つオブジェクト。
 * 例：{ ja: "こんにちは", en: "Hello" }
 */
export interface Localized {
  [k: string]: unknown;
}
export interface Free {
  /**
   * このユーザーコンテンツは商用利用など含めて自由に使用できることを示します。
   */
  name: "free";
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
  [k: string]: unknown;
}
export interface Nicovideo {
  /**
   * このユーザーコンテンツはニコニコ動画での親作品登録が必要であることを示します。
   */
  name: "nicovideo";
  /**
   * 親作品登録が必須ではないことを示します。省略した場合、親作品登録は必須です。
   */
  omittable?: boolean;
  /**
   * 親作品登録に使うID。`smXXXXXX`や`nmXXXXXX`の形式で指定してください。
   */
  id: string;
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
  [k: string]: unknown;
}
export interface Custom {
  /**
   * このユーザーコンテンツは独自の利用規約を持つことを示します。
   */
  name: "custom";
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text: Single | Localized;
  [k: string]: unknown;
}
export interface Unknown {
  /**
   * 将来の拡張用。
   */
  name: string;
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
  [k: string]: unknown;
}
/**
 * バンドルを定義します。
 * 複数ファイルをまとめたアーカイブをダウンロードし、その中から必要なファイルを取り出すために使用します。
 * バンドル名をキー、そのバンドルのURLを値とするオブジェクトです。
 * バンドル名は`[a-z0-9_]+`にマッチする必要があります。
 * 今現在、以下のアーカイブ形式がサポートされています：
 * - zip（`.zip`）
 * - tar.gz（`.tar.gz`または`.tgz`）
 */
export interface RecordHttpUrl {
  [k: string]: unknown;
}
