/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Single = string;
/**
 * 多言語対応文字列または単一言語文字列。
 * 例1："Hello"
 * 例2：{ ja: "こんにちは", en: "Hello" }
 */
export type MaybeLocalizedString = Single | Localized;
/**
 * http・httpsのURL。
 */
export type HttpUrl = string;

export interface Registry {
  /**
   * レジストリのバージョン。現在は1のみサポートしています。
   * 破壊的変更が行われた場合にのみ、この値が増加します。
   */
  registry_version: 1;
  /**
   * レジストリの名前。
   */
  name: string;
  /**
   * このレジストリの説明。
   */
  summary: Single | Localized;
  /**
   * このレジストリのホームページ。
   */
  homepage?: string;
  /**
   * このレジストリに含まれるユーザーコンテンツの一覧。
   */
  contents: {
    /**
     * マニフェストのバージョン。現在は1のみサポートしています。
     * 将来的にマニフェストの仕様が変わる可能性があるため、このフィールドを使用してバージョン管理を行います。
     * 破壊的変更が行われた場合にのみ、この値が増加します。
     */
    manifest_version: 1;
    /**
     * ユーザーコンテンツの一意な識別子。/^(?<author>[a-z0-9_]+)-(?<content_name>[a-z0-9_-]+)$/ にマッチし、かつ、
     * `-`が連続しない文字列である必要があります。
     * ここで、authorは作者名、content_nameはユーザーコンテンツの名前を表します。
     * コンテンツ名では`-`と`_`をどちらも使用することができ、それらは以下のように使用するべきです。
     * - `-`は概念の区切りに使用する。
     * - `_`は単語の一部に使用する。
     * 例えば、`sevenc_nanashi-aviutl2_rs-ffmpeg_output`は：
     * - 「sevenc_nanashi」という作者の、
     * - 「aviutl2_rs」というものに関する、
     * - 「ffmpeg_output」というユーザーコンテンツ
     * を表します。
     * なお、`content_name`は1単語でも構いません。
     */
    id: string;
    /**
     * ユーザーコンテンツの名前。任意の文字列を指定できます。
     */
    name: string;
    /**
     * ユーザーコンテンツの簡易的な説明。1行で収まるようにしてください。
     */
    summary: Single | Localized;
    /**
     * ユーザーコンテンツのタグ。
     * タグは自由に追加できますが、以下のタグはUIで特別に扱われます：
     * - `#alias`：エイリアス
     * - `#alias-effect`：フィルタ効果エイリアス
     * - `#alias-object`：オブジェクトエイリアス
     * - `#default`：パレット
     * - `#palette`：パレット（#defaultのエイリアス）
     * - `#figure`：図形
     * - `#language`：言語ファイル
     * - `#plugin`：プラグイン
     * - `#plugin-input`：入力プラグイン
     * - `#plugin-output`：出力プラグイン
     * - `#script`：スクリプト
     * - `#script-anm`：アニメーション効果スクリプト
     * - `#script-obj`：カスタムオブジェクトスクリプト
     * - `#script-cam`：カメラ制御スクリプト
     * - `#script-scn`：シーンチェンジスクリプト
     * - `#script-tra`：トラックバー移動方法スクリプト
     * - `#theme`：テーマ
     * - `#transition`：トランジション
     */
    tags?: MaybeLocalizedString[];
    /**
     * ユーザーコンテンツのバージョン。`X.Y.Z(-.+)?`の形式に従う必要があります。
     * 例: "1.0.0", "0.1.0", "2.3.4-beta"
     */
    version: string;
    /**
     * ユーザーコンテンツのバージョン番号。
     */
    version_number?: number;
    /**
     * ユーザーコンテンツの作者。
     *
     * @minItems 1
     */
    authors: [
      {
        name: MaybeLocalizedString;
        url?: HttpUrl;
      },
      ...{
        name: MaybeLocalizedString;
        url?: HttpUrl;
      }[]
    ];
    /**
     * ユーザーコンテンツを使用する際の利用規約。
     * このユーザーコンテンツを使用したときの規約のみを記述してください。（例えば、再配布の規約などは含めないでください）
     */
    license: Free | Nicovideo | Custom | Unknown;
    /**
     * ユーザーコンテンツのホームページ。
     */
    homepage?: string;
    /**
     * 多言語対応文字列または単一言語文字列。
     * 例1："Hello"
     * 例2：{ ja: "こんにちは", en: "Hello" }
     */
    description?: Single | Localized;
    /**
     * このユーザーコンテンツのマニフェストへのURL。
     * 単体のマニフェストとは違い、このフィールドは必須です。
     */
    manifest_url: string;
  }[];
}
/**
 * 多言語対応文字列。キーにロケール、値にそのロケールでの文字列を持つオブジェクト。
 * 例：{ ja: "こんにちは", en: "Hello" }
 */
export interface Localized {}
export interface Free {
  /**
   * このユーザーコンテンツは商用利用など含めて自由に使用できることを示します。
   */
  name: "free";
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
}
export interface Nicovideo {
  /**
   * このユーザーコンテンツはニコニコ動画での親作品登録が必要であることを示します。
   */
  name: "nicovideo";
  /**
   * 親作品登録が必須ではないことを示します。省略した場合、親作品登録は必須です。
   */
  omittable?: boolean;
  /**
   * 親作品登録に使うID。`smXXXXXX`や`nmXXXXXX`の形式で指定してください。
   */
  id: string;
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
}
export interface Custom {
  /**
   * このユーザーコンテンツは独自の利用規約を持つことを示します。
   */
  name: "custom";
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text: Single | Localized;
}
export interface Unknown {
  /**
   * 将来の拡張用。
   */
  name: string;
  /**
   * 多言語対応文字列または単一言語文字列。
   * 例1："Hello"
   * 例2：{ ja: "こんにちは", en: "Hello" }
   */
  text?: Single | Localized;
}
